version: '3.8'

services:
  spark:
    build: .
    container_name: spark-container
    environment:
      - PYSPARK_PYTHON=python3
      - SPARK_HOME=/opt/spark
    ports:
      - "8080:8080"
      - "8888:8888"
    volumes:
      - .:/app
    command: ["/bin/bash", "-c", "start-all.sh && jupyter notebook --ip=0.0.0.0 --no-browser --allow-root --NotebookApp.token=''"]

  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka-container
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper-container
    ports:
      - "2181:2181"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    container_name: elasticsearch-container
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"